services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: clouduser
      POSTGRES_PASSWORD: cloudpass
      POSTGRES_DB: cloudnotes
    ports:
      - "5433:5432"
